apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-consumer
  labels:
    app: pubsub-consumer
spec:
  replicas: 1
  template:
    metadata:
      name: pubsub-consumer
      labels:
        app: pubsub-consumer
    spec:
      containers:
        - name: pubsub-consumer
          image: mpolatcan/cloudday-pubsub-consumer
          imagePullPolicy: Always
          env:
            - name: "GCP_PROJECT_ID"
              value: "mpolatcan-sandbox" # Enter your project id
            - name: "PUBSUB_TOPIC_NAME"
              value: "test-topic"
            - name: "PUBSUB_SUBSCRIPTION_ID"
              value: "test-subscription"
            - name: "GCP_AUTH_FILE_LOCATION"
              value: "/auth/mpolatcan-sandbox-2b957d5c708c.json" # Enter your auth filename.json
          volumeMounts:
            - mountPath: /auth
              name: gke-auth-file-vol
      restartPolicy: Always
      volumes:
        - name: gke-auth-file-vol
          secret:
            secretName: gke-auth-file-secret
  selector:
    matchLabels:
      app: pubsub-consumer
