apiVersion: v1
kind: Service
metadata:
  name: api-server-svc
  labels:
    app: api-server
spec:
  selector:
    app: api-server
  ports:
    - name: api-server-port
      port: 3000
      targetPort: 5000
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-server-ingress
  labels:
    app: api-server
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: api-server-svc
              servicePort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  replicas: 1
  template:
    metadata:
      name: api-server
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: us.gcr.io/cloud-day-233307/api-server:v1
          imagePullPolicy: Always
          workingDir: /
          env:
            - name: "API_SERVER_PORT"
              value: "5000"
            - name: "GCP_PROJECT_ID"
              value: "cloud-day-233307"
            - name: "PUBSUB_TOPIC_NAME"
              value: "test-topic"
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              port: 5000
              path: /
            initialDelaySeconds: 1
            failureThreshold: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              port: 5000
              path: /
            initialDelaySeconds: 1
            failureThreshold: 3
            periodSeconds: 3
      restartPolicy: Always
  selector:
    matchLabels:
      app: api-server
