apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: api-server-hpa
spec:
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - external:
        metricName: loadbalancing.googleapis.com|https|request_count
        targetAverageValue: 100
      type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-server
