apiVersion: v1
kind: Service
metadata:
  name: sample-metrics-app
  namespace: test
  labels:
    app: sample-metrics-app
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: 8080
  selector:
    app: sample-metrics-app
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: sample-metrics-app
  name: sample-metrics-app
  namespace: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-metrics-app
    spec:
      containers:
        - image: luxas/autoscale-demo:v0.1.2
          name: sample-metrics-app
          ports:
            - name: web
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
